---

- name: "APP | Deploy SupervisorD Reverb Configuration"
  become: true
  ansible.builtin.template:
    src: "{{ ansistrano_deploy_from }}/{{ app_supervisor_reverb_config_path | default('build/deploy/supervisor/' + app_environment + '-reverb.conf.j2') }}"
    dest: "{{ app_supervisor_config_dest | default('/etc/supervisord.d') }}/{{ app_domain }}-reverb.ini"
    owner: "{{ app_deployer_user | default(ansible_user) }}"
    group: "{{ app_deployer_group | default(ansible_user) }}"
    mode: "0644"
  tags:
    - server
    - app
    - post
